[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
# You can define any specific settings for setuptools here.

[tool.setuptools.build]
jobs = 2  # Limit the number of parallel jobs to 2 to reduce memory usage.
